### ISSUE TITLE
Support Date/Time types

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/telemetry-batch-view#21]
Avro 1.8.0 added support for date/time types (see [AVRO-793](https://issues.apache.org/jira/browse/AVRO-739)).  It would be nice to support these in the parquet datasets too (though I'm not sure that will even work...)

**Comment by vitillo** [comment]
See #31.

**Comment by mreid-moz** [comment]
Do you mean this comment in particular?

> Nevermind, Spark 1.6 uses an older Avro version and as such we can't upgrade the one used in our job without the likelihood of entering the JAR hell.

What about with the deployment of Spark 1.6?

**Comment by mreid-moz** [comment]
Ehh, reading fail.  Never mind, somehow I read your 1.6 as a 1.5 :)
