### ISSUE TITLE
Don't use the 'info.flashVersion' field

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/telemetry-batch-view#45]
According to the [Telemetry docs](https://gecko.readthedocs.org/en/latest/toolkit/components/telemetry/telemetry/main-ping.html), the `info.flashVersion` field is obsolete.
We should look in the `environment.addons.activePlugins` field to determine the (latest?) installed flash version. 

An example of code that does this is [here](https://github.com/mozilla-services/data-pipeline/blob/master/hindsight/modules/fx/ping.lua#L82-L105).

**Comment by vitillo** [comment]
Do we have a Bug filed for this on Bugzilla?

**Comment by mreid-moz** [comment]
No, nobody has asked for it, I just happened to notice it while working on another bug (bug 1260847)

**Comment by mreid-moz** [comment]
fwiw, #48 adds a utility function `getFlashVersion` for pulling this info out of the environment.

**Comment by mreid-moz** [comment]
The code that should be removed is [here](https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/streams/Longitudinal.scala#L735), and the replacement function can be found [here](https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/streams/main_summary/Utils.scala#L77).
