### ISSUE TITLE
Corrupt SEARCH_COUNTS blobs should not be silently discarded

### ISSUE THREAD

**Issue by SamPenrose** [mozilla/telemetry-batch-view#58]
Unparseable SEARCH_COUNT key or sum values are silently discarded:

https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/streams/main_summary/Utils.scala#L105
https://github.com/mozilla/telemetry-batch-view/blob/master/src/test/scala/MainSummaryTest.scala#L299

Let's not do this. How about returning something like this if the key is corrupt:

    "engine" -> "__CORRUPTED",
    "source" -> "__CORRUPTED"
and if sum.toInt fails, setting the value to 0?

**Comment by mreid-moz** [comment]
What if we introduce a new (nullable) field for `key`, and make the other three fields nullable too.
Then if we fail to parse the histogram key into an `engine` / `source`, we set the `key` field instead (leaving the other two null), and if we fail to parse the `sum` field, we set the `count` to null.

This would give us the ability to do "light" investigation of bad keys, as well as showing at least the scale of any problem with unparseable sums.

**Comment by SamPenrose** [comment]
Setting engine and source null instead of to a sentinel value is fine. I don't want key but don't object to it. We could certainly set count to null. If we set it to 0, then integer operations still work and the signal is available. If we set it to null then non-SQL access has to test inside each operation, which is a cost.

C.f. issue #59 , where I propose adding 3 new fields to each struct in search_counts.

**Comment by mreid-moz** [comment]
What's the goal / analytic question you want to solve?

**Comment by SamPenrose** [comment]
My goal is to communicate search results accurately. In the short term, this change would allow me to say "0.8% of provider-source values are unreadable, and 1.1% of counts are unreadable" or whatever the real values are. In the medium term we can decide whether to investigate causes.

**Comment by mreid-moz** [comment]
Ok, let's go with the simplest thing and null out those fields in the case where they contain unexpected data.

Most aggregate operations should be resilient to null values, and you can also use the "fill" functions. 
<img width="532" alt="screen shot 2016-04-15 at 11 29 42 am" src="https://cloud.githubusercontent.com/assets/969479/14564572/8358475e-02fd-11e6-80d1-5431b6ca113b.png">

 Does that seem reasonable?

**Comment by SamPenrose** [comment]
That sounds great, thanks so much.

**Comment by mreid-moz** [comment]
Resolved by https://github.com/mozilla/telemetry-batch-view/pull/79
