### ISSUE TITLE
Process search partnership information in MainSummary.scala

### ISSUE THREAD

**Issue by SamPenrose** [mozilla/telemetry-batch-view#59]
For each value in a main ping's /payload/keyedHistograms/SEARCH_COUNTS object, we currently extract (engine, source, count). For reporting purposes we also want to know:

  1) which partner distribution, if any, does the ping's distributionid map to
  2) is the search provider via an official plugin
  3) is the search renumerable (a subset of previous)

These three fields (a short string, often null, and two booleans) are a function of engine, source, and a conceptually small, infrequently changing configuration state published under:

    https://hg.mozilla.org/build/partner-repacks/file/tip/
    http://l10n.mozilla-community.org/~flod/p12n/searchplugins.json

Can we add a mechanism for loading that configuration information and set three new fields inside the struct:

  partner string default null
  is_official boolean default 0
  is_renumerable boolean default 0

If so, I am happy to provide the PR

**Comment by vitillo** [comment]
Please open a Bug on Bugzilla if this is still required.
